services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_log:/var/log/postgresql
    env_file:
      - env/.env.pg
  http_docs:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/docs/swagger.json
    volumes:
      - ./docs:/docs
  nginx:
    image: prod
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - http_docs
      - orchestrator
  rabbitmq:
    image: rabbitmq:3-management-alpine
    env_file: env/.env.rmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
volumes:
  db_data:
  db_log:
  rabbitmq_data:
  rabbitmq_log:
