services:
  backend:
    image: golang:1.21-alpine
    command: go run cmd/main.go
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
  http_docs:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/api-docs/swagger.json
    volumes:
      - ./api-docs:/api-docs
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - http_docs
volumes:
  db_data: