FROM golang:1.22 as build

WORKDIR /go/src/app
COPY go.mod go.mod
COPY go.sum go.sum

RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /go/bin/app orchestrator/cmd/main.go
RUN CGO_ENABLED=0 GOOS=linux go build -o /go/bin/agent agent/cmd/main.go

FROM alpine:latest

COPY --from=build /go/bin/app /app
COPY --from=build /go/bin/agent /agent

# Set the entry point and default command
CMD ["/app"]
